apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeaction
  name: kubeaction-server
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: kubeaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeaction-server
  labels:
    app: kubeaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeaction
  template:
    metadata:
      labels:
        app: kubeaction
    spec:
      containers:
        - name: controller
          image: wesky93/kubeaction-controller:latest
          imagePullPolicy: Always
          env:
            - name: KUBEACTION_JOB_IMAGE
              value: wesky93/kubeaction-job:latest
            - name: KUBECTL_CONFIG_MODE
              value: 'false'
            - name: DIND_MODE
              value: 'true'
            - name: API_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: API_SERVICE
              value: kubeaction-server
            - name: API_PORT
              value: '5000'
            - name: KUBE_PROXY
              value: "http://localhost:8080"
        - name: api-server
          image: wesky93/kubeaction-controller:latest
          imagePullPolicy: Always
          command:
            - python
            - /src/app.py
          ports:
            - containerPort: 5000
          env:
            - name: API_PORT
              value: '5000'
            - name: KUBE_PROXY
              value: "http://localhost:8080"
        - name: kubectl-proxy
          image: spaceone/kubectl-proxy:latest
          ports:
            - containerPort: 8080


