apiVersion: kubeaction.spaceone.dev/v1alpha1
kind: Flow
metadata:
  name: simple-flow-3
spec:
  events:
    schedule:
      - cron:  '*/1 * * * *'
  jobs:
    first:
      runs-on: ubuntu-latest
      steps:
        - name: let's Run!
          id: request
          run: echo 'test'
        - name: run one more time
          id: request
          run: |
            echo 'second' |
            pip3 list
        - uses: actions/javascript-action@v1
          with:
            milliseconds: 3000
